### ISSUE TITLE
[debug mode] Opening a Diagram display traces on the console

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#19]
When opening a diagram , on the console, the "jsonrpc" data structure is displayed, we should put this in a debug level mode, not necessary show it on the console log all the times unless we are in debug mode.

**Comment by JanKoehnlein** [comment]
Fixed

**Comment by hexa00** [comment]
Please link the commit...

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/yang-sprotty/commit/0f9d9b15f83419c6d68820785b1f8916b52f5ff1
