### ISSUE TITLE
Namespace char replacement "-" by "/"

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#23]
If you select the file: "example-3-a.yang" , hover the diagram will open a dialog with the information and the Namespace for the file will be "example-3/a". Why do we replace the last"-a" by "/a"  and the end?
![peek 2017-10-23 hovernamespace](https://user-images.githubusercontent.com/419051/31896406-b01ed88a-b7e1-11e7-880d-188cce7a07b2.gif)

**Comment by JanKoehnlein** [comment]
The model defines 
```
module example-3-a {
  yang-version "1.1";
  namespace "http://example.com/example-3/a";
```

We show the module name in th ediagram and the namespace in the hover. Do I miss something?

**Comment by lmcbout** [comment]
Explanation is fine with me
