### ISSUE TITLE
No menu items available in  Selection menu

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#26]
Menu "Selection" available, but all options aregreyed out. Should we have this menu option available?
![peek 2017-10-23 selectionmenu](https://user-images.githubusercontent.com/419051/31898641-8ab66c24-b7e7-11e7-97f9-293c4ed1e27b.gif)

**Comment by JanKoehnlein** [comment]
Most of these don't make sense for the diagram. Which ones would you like to use?
I don't think that Theia can deactivate entire menus.

**Comment by lmcbout** [comment]
If we use the diagram display and if none of the menu items apply to any diagram, then the menu "Selection" should not clutter the menu bar, it should be invisible when the user is editing/viewing a diagram

**Comment by JanKoehnlein** [comment]
Then this issue should go to Theia :-)

**Comment by lmcbout** [comment]
Issue move to THEIA: https://github.com/theia-ide/theia/issues/731
