### ISSUE TITLE
Accelerator for some commands: "Center", "Fit to screen"

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#30]
Can we get accelerator key for : "Center", "Fit to screen"

**Comment by JanKoehnlein** [comment]
There is (CTRL=CMD on Mac)
CTRL-F for "Fit to Screen"
CTRL-E for "Export"

These keybindins used to work as well
CTRL-C for "Center"
CTRL-Z for "Undo"
CTRL-SHIFT-Z for "Redo"
These seem to be broken as Theia has bound them in the meantime. I think we should go for a different modifier key for all these shortcuts to avoid this ambiguities. Suggestions are welcome.

**Comment by lmcbout** [comment]
I am on UBUNTU and CTRL-C  does not work
Also, there is no indication about the key bindings in the Diagram sub-menu. We cannot let the end-user try every combination to find-out the key-bindings for each command

**Comment by JanKoehnlein** [comment]
Changed to ALT-C, ALT-F and ALT-E and added accelerators to menu

**Comment by hexa00** [comment]
Would be nice to link with the commit ?

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/theia-sprotty/commit/b49c2f8e472efc78242cab361643626772d64783
