### ISSUE TITLE
Add an opener for SVG files

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#32]
Try to open the exported diagram with the option "Files -> Open with -> Yang Diagram" ==> open an editor which does not show the diagram at all.
![peek 2017-10-23 exportopen](https://user-images.githubusercontent.com/419051/31903034-dee16ac6-b7f4-11e7-96dd-570e2cf68836.gif)

**Comment by hexa00** [comment]
I guess this is expected sing the svg is not a diagram. It is the exported svg.
We should have however a opener for the svg directly.

**Comment by JanKoehnlein** [comment]
changed the title

**Comment by JanKoehnlein** [comment]
The SVG is going to look exactly like the 'live' diagram, so I fear users are going to be pretty confused when it does not behave the same way.

**Comment by hexa00** [comment]
I don't think we can miss out of a svg viewer because of that however.

User should know from the filename or yang should display something that indicates to the user what he can do in there?
