### ISSUE TITLE
[keyBinding] Missing keyboard key binding for Delete

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#33]
Select a file in the navigator , then use the keyboard and use the delete button to delete the file ==> nothing happen. (Key binding to the delete button needed"
![peek 2017-10-23 delete](https://user-images.githubusercontent.com/419051/31903205-73e06b18-b7f5-11e7-877f-e472e582157e.gif)

**Comment by hexa00** [comment]
This related to theia's navigator. It's not related to yang.

Please create the issue there.

**Comment by lmcbout** [comment]
issue moved to THEIA:
https://github.com/theia-ide/theia/issues/729
