### ISSUE TITLE
Yangster image should be up-to-date on docker hub

### ISSUE THREAD

**Issue by epatpol** [theia-ide/yangster#40]
I.e https://hub.docker.com/r/typefox/yangster/

We should find a way to update this one to the latest master when possible, either by having travis push to docker hub, or having the docker hub triggering a re-build of the image when master changed.

**Comment by epatpol** [comment]
From what I understand, we can configure the hub to automatically build on code changes, https://docs.docker.com/docker-hub/builds/, and from what I've seen in other docker projects, they usually have a tagged "released" image and a "next" or "latest" image which is based on the current master. I think it would be a good idea to have this.

**Comment by hexa00** [comment]
Just to clarify: 

latest = latest released version
next = latest commit

**Comment by epatpol** [comment]
I think we could have a travis ci job that on (commit-to-master) would push to the "next" tag. However for the "latest" tag I'm not sure how to do it automatically, I was thinking maybe we could have a job that we trigger manually that would push  a docker image for a certain commit id.

**Comment by hexa00** [comment]
Yes actually I think we should have the following procedure:

  - Changes all the extensions version to version x
  - Commits that change to master
  - tags master with version x
  - Runs that through CI 
  - Builds docker image with CI 
  - Test docker image on CI 

If CI is OK:

Have a script that:
  
  - Publishes to npm (by doing a git clone of the git tag and publishing
  - the result)
  - Publishes docker image based on git the new git-tag
  
This should be the same for theia.

**Comment by epatpol** [comment]
As of right now is yangster on npm?

**Comment by hexa00** [comment]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/yangster
npm ERR! 404 
npm ERR! 404  'yangster' is not in the npm registry.
nope

**Comment by hexa00** [comment]
theia-yang-extension is not either

**Comment by JanKoehnlein** [comment]
neither is yang-sprotty, theia-sprotty.

**Comment by JanKoehnlein** [comment]
I have published the npm packages.

**Comment by JanKoehnlein** [comment]
The auto-build on docker-hub still points to the old repository location.

**Comment by epatpol** [comment]
As of right now does the auto-build push a new dockerfile on new commits to master?

**Comment by JanKoehnlein** [comment]
Yes, it does, but it listens to the old repo. I have just created a new build with the new repo. It's building now, should take a while... 

We could also make it rebuild when tag names match a given regexp.

**Comment by epatpol** [comment]
@JanKoehnlein thanks for fixing the automated build.

Yes according to the [dockerhub documentation](https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build) it looks pretty flexible with regexp. The thing is there's no release cycle yet afaik, i.e which numbers should we give to releases, when to release etc.

**Comment by JanKoehnlein** [comment]
The main problem is that yangster and yang-eclipse depend on yang-lsp, i.e. the respective builds consume its built artifacts. All of them can have different version numbers.

So this is what I got working and what I feel is good enough for now:
On Jenkins:
- a successful build of [yang-lsp](http://services.typefox.io/open-source/jenkins/job/yang-lsp/) triggers the rebuild of [yangster](http://services.typefox.io/open-source/jenkins/job/yangster/) and [yang-eclipse](http://services.typefox.io/open-source/jenkins/job/yang-eclipse/)

On Dockerhub:
- a commit to yangster/master triggers the build of a Docker image yangster/latest
- adding a version tag on yangster triggers the build of a Docker image yangster/release-{tag}

Dockerhub's automatic builds directly listen to Github, so this was the easiest way. The backside is that we don't get a new Docker image when we just change the language server. If we want to build the Docker image based on the Jenkins job, we'd have to do that ourselves and upload it to dockerhub afterwards.

For publishing to npm and jcenter, I still prefer a manual process.

**Comment by hexa00** [comment]
Just a comment about naming.

Could we align this with npm naming scheme for theia and have:

  Master creating a docker image with yangster/next
  Latest release to yanger/releast-{tatest tag}
  Release to yanger/release-{tag} ?

**Comment by JanKoehnlein** [comment]
I doubt we are going to maintain multiple versions of yangster at the same time (at least not in the near future), so I switched the naming from _latest_ to _next_ and added an extra build for _release-latest_.
