### ISSUE TITLE
outline view not populated as expected

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/yangster#45]
Looking at the outline view in Yangster, using the "mytest.yang" example source file, it seems that the view is only partially populated, having a single entry: "my-type". Bug? 

![image](https://user-images.githubusercontent.com/25749063/32784345-9236b210-c91c-11e7-897c-355f84939b1c.png)

**Comment by JanKoehnlein** [comment]
Cannot reproduce with the latest version. Could it be your YANG language server is no longer running?

**Comment by marcdumais-work** [comment]
Not sure what was wrong, but I just tried again and now the outline view works.
