### ISSUE TITLE
Error adding Theia git extension as dependency

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/yangster#47]
Trying to fix #46, I encountered this issue.  
I gave this a try: I added a dependency to the theia git extension in package.json. It builds fine but there's an exception in the frontend application, preventing it from starting:

(see the change here: https://github.com/marcdumais-work/yangster/commit/5d4840d9033ea858024c7c59d7536538d764aa00 )

```
index.js:44 Error: Cannot apply @injectable decorator multiple times.
    at injectable.js:8
    at DecorateConstructor (Reflect.ts:1090)
    at Object.decorate (Reflect.ts:284)
    at _decorate (decorator_utils.js:42)
    at Object.decorate (decorator_utils.js:55)
    at Object.defineProperty.value (widget.ts:13)
    at __webpack_require__ (bootstrap 57bab4548ecc5c842def:688)
    at fn (bootstrap 57bab4548ecc5c842def:109)
    at Object.c (index.ts:8)
    at __webpack_require__ (bootstrap 57bab4548ecc5c842def:688)
module.exports.Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.reason @ index.js:44
Promise rejected (async)
(anonymous) @ index.js:41
__webpack_require__ @ bootstrap 57bab4548ecc5c842def:688
Object.defineProperty.value @ bootstrap 57bab4548ecc5c842def:789
(anonymous) @ bootstrap 57bab4548ecc5c842def:789
```

**Comment by akosyakov** [comment]
Could you attach package.json please?

**Comment by marcdumais-work** [comment]
Hi @akosyakov here you go : 

``` javascript
{
    "private": true,
    "name": "yangster-app",
    "version": "0.1.3",
    "license": "Apache-2.0",
    "dependencies": {
        "@theia/core": "latest",
        "@theia/editor": "latest",
        "@theia/filesystem": "latest",
        "@theia/git": "latest",
        "@theia/languages": "latest",
        "@theia/markers": "latest",
        "@theia/monaco": "latest",
        "@theia/navigator": "latest",
        "@theia/preferences": "latest",
        "@theia/process": "latest",
        "@theia/terminal": "latest",
        "@theia/typescript": "latest",
        "@theia/workspace": "latest",
        "theia-yang-extension": "0.1.3"
    },
    "devDependencies": {
        "@theia/cli": "latest"
    },
    "scripts": {
        "prepare": "theia build",
        "start": "theia start --root-dir=../workspace",
        "start:backend:socket": "node ./src-gen/backend/main.js --root-dir=../workspace --YANG_LSP=5007 --port=3000 --loglevel=debug",
        "watch": "theia build --watch"
    },
    "theia": {
        "target": "browser"
    }
}
```

**Comment by akosyakov** [comment]
And you run `yarn` right?

**Comment by akosyakov** [comment]
I cannot reproduce, what i did:
- created package.json
- `yarn`
- `npx theia start .`

**Comment by marcdumais-work** [comment]
yes, I ran yarn. I just started with a fresh clone and was able reproduce the issue, on latest master. Here's that I did: 

git clone --recursive https://github.com/theia-ide/yangster.git && cd yangster
yarn
cd yangster-app
yarn start

# at this point, yangster starts normally.

gedit package.json  # add git dependency to package.json:
cd ..
yarn
cd yangster-app
yarn start

# now I get the error reported above: "Error: Cannot apply @injectable decorator multiple times."

**Comment by hexa00** [comment]
@marcdumais-work I can reproduce using your method

**Comment by akosyakov** [comment]
it is because your yarn.lock has outdated version "0.2.0" for already installed extensions. Update it first with `yarn --force`.

**Comment by JanKoehnlein** [comment]
You have to delete the `yarn.lock` file before rebuilding. It causes stale Theia extensions to persist and the newer versions which are dependencies of the new extension to be installed in parallel, yielding the inject bug.

**Comment by JanKoehnlein** [comment]
Added the Git extension in 04be599686eefa6b538ba6eae1d237134a44b7e9

**Comment by marcdumais-work** [comment]
I tried deleting yarn.lock and yangster did compile. Opening a WS with a git repo, I get the git widget visible, thanks!
