### ISSUE TITLE
Would be better to support port and host both

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yangster#48]
https://github.com/theia-ide/yangster/blob/cd8d38e3024fb41dd77804a1c59089432e27491c/theia-yang-
extension/src/backend/backend-extension.ts#L50
socket.connect(socketPort)

Here in the current implementation, only port is allowed.
I think to support both port and host will be much useful.

Required Socket API
[NodeJs Socket.connect API](https://nodejs.org/api/net.html#net_socket_connect_port_host_connectlistener)

**Comment by svenefftinge** [comment]
What is the usecase you envision? The language server needs to see the same file system than the backend.

**Comment by huyuwen** [comment]
Aha, I didn't know the designed purpose before.
OK, I can understand that.

Please close this issue then.

**Comment by svenefftinge** [comment]
ok
