### ISSUE TITLE
Need to publish new "latest" version of yangster?

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/yangster#58]
I think since the recent Theia 0.3.8 release, Theia applications that contain the ```theia-yang-extension@latest``` fail at runtime when trying to open a file. Exception:

```
reflection_utils.js:33 Uncaught (in promise) Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
    at u (reflection_utils.js:33)
    at Object.t.getDependencies (reflection_utils.js:11)
    at planner.js:106
    at Array.forEach (<anonymous>)
    at e (planner.js:94)
    at Object.t.plan (planner.js:129)
    at container.js:316
    at e._get (container.js:309)
    at e.get (container.js:228)
    at e.editorProvider (monaco-frontend-module.ts:53)
```

The current ```next``` version now available on npm does not seem to have this issue. 

I think we need to publish an updated ```latest``` version of this extension, and possibly of dependencies (sprotty, etc).

**Comment by JanKoehnlein** [comment]
Done.

**Comment by marcdumais-work** [comment]
Thanks @JanKoehnlein - I quickly built a Theia app that includes the yang extension "latest" and the file open problem is gone.
