### ISSUE TITLE
Type shows as null for referenced types

### ISSUE THREAD

**Issue by andreasjakobik** [theia-ide/yangster#66]
Hi,

Seems referenced types are not looked up properly.

Consider Yang

	import ietf-yang-types {
		prefix yang;
	}
...
           leaf time {
                type yang:date-and-time;
            }
...

The diagram will show "null" as type for the leaf, see attached picture.

![image](https://user-images.githubusercontent.com/1358557/45807162-20d0ce80-bcc3-11e8-83ef-922578782c2e.png)

Thanks,
Andreas

**Comment by JanKoehnlein** [comment]
Fixed by 7973d24479194ab028ef9f1cb6702eea43d9cd4c
