### ISSUE TITLE
Error running yarn

### ISSUE THREAD

**Issue by melaasar** [theia-ide/yangster#70]
Hi. I tried running yarn on yangster but I get the following error:

src/frontend/yangdiagram/di.config.ts(22,38): error TS2345: Argument of type 'typeof TheiaKeyTool' is not assignable to parameter of type 'new (...args: any[]) => KeyTool'.
  Type 'TheiaKeyTool' is not assignable to type 'KeyTool'.
    Property 'actionDispatcher' is protected but type 'KeyTool' is not a class derived from 'KeyTool'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any idea what's going on?

**Comment by jabelk** [comment]
I get same/similar error, running on 
 yarn --version                 
1.12.3
on OS X 10.13.5
Python 2.7.15
npm 6.4.1

[link to output](https://gist.github.com/jabelk/57625fab90ecb82d92c37460a922fd20)

**Comment by JanKoehnlein** [comment]
See https://github.com/theia-ide/yangster/issues/69

**Comment by svenefftinge** [comment]
I added an intermediate fix, by synching the version of sprotty we use.
